services:
  xinference:
    image: xprobe/xinference:latest
    container_name: xinference
    ports:
      - "9998:9998"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always