[project]
name = "myagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.0",
    "fastmcp>=2.13.0",
    "openai>=1.0.0,<2.0.0",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
]
